body_font_family:
  default: Semplicita, sans-serif
  type: enum
  choices:
    - -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji"
    - Lato, Arial, sans-serif

heading_font_family:
  default: Semplicita, sans-serif
  type: enum
  choices:
    - -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji"
    - Lato, Arial, sans-serif

editor_font_family:
  default: -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji"
  type: enum
  choices:
    - Semplicita, sans-serif
    - Lato, Arial, sans-serif